# Generated by Django 3.2.4 on 2022-01-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер договора')),
                ('year', models.IntegerField(blank=True, verbose_name='Номер договора')),
                ('desciption', models.IntegerField(blank=True, verbose_name='Номер договора')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка на фильм')),
                ('sourse', models.CharField(max_length=100, verbose_name='Ресурс фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
