# Generated by Django 3.2.4 on 2022-01-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='desciption',
            field=models.IntegerField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='sourse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ресурс фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
