# Generated by Django 3.2.4 on 2022-01-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220107_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='desciption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
