# Generated by Django 3.2.4 on 2022-01-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_film_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='desciption',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Описание'),
        ),
    ]
