# Generated by Django 4.0 on 2022-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220201_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinOtchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('type', models.CharField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('wb_price', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Цена на вб')),
                ('selling_price', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Цена по которой продал вб')),
                ('kvv', models.FloatField(blank=True, max_length=10000, null=True, verbose_name='Размер комисии')),
                ('reward', models.CharField(blank=True, max_length=10000, null=True, verbose_name='К перечислению продавцу')),
                ('logistics_amount', models.FloatField(blank=True, null=True, verbose_name='Цена логистики')),
            ],
            options={
                'verbose_name': 'Otchet',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='greatq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
